# Generated by Django 6.0.4 on 2026-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleitems_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleattributes',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='change_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Change Due'),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card')], max_length=4, null=True, verbose_name='Payment Method'),
        ),
    ]
