# Generated by Django 6.0.4 on 2026-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleattributes_amount_paid_saleattributes_change_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleattributes',
            name='card_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid (Card)'),
        ),
        migrations.AlterField(
            model_name='saleattributes',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid (Cash)'),
        ),
        migrations.AlterField(
            model_name='saleattributes',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MIXED', 'Mixed')], max_length=5, null=True, verbose_name='Payment Method'),
        ),
    ]
