# Generated by Django 6.0.4 on 2026-09-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_show_on_pos_product_show_on_pos'),
        ('sales', '0004_saleattributes_card_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_pins', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_pins', to='products.product')),
            ],
            options={
                'verbose_name': 'POS Pin',
                'verbose_name_plural': 'POS Pins',
                'ordering': ['position'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('product__isnull', True)), models.Q(('category__isnull', True), ('product__isnull', False)), _connector='OR'), name='pospin_exactly_one_of_category_or_product')],
            },
        ),
    ]
