# Generated by Django 6.0.4 on 2026-09-12 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_show_on_pos_product_show_on_pos'),
        ('sales', '0005_pospin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemVoidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('action', models.CharField(choices=[('REMOVE_LINE', 'Removed one line'), ('VOID_SALE', 'Voided whole sale')], max_length=15)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_item_voids', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_item_voids', to='products.product')),
            ],
            options={
                'verbose_name': 'Removed Sale Item',
                'verbose_name_plural': 'Removed Sale Items',
                'ordering': ['-removed_at'],
            },
        ),
    ]
