# Generated by Django 6.0.4 on 2026-09-16 13:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitemvoidlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('RETURN_COMPLAINT', 'Return / Complaint'), ('OPERATOR_ERROR', 'Operator Error'), ('TAX_BASE_REDUCTION', 'Reduction of Tax Base')], max_length=20)),
                ('time_of_refund', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.saleattributes')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-time_of_refund'],
            },
        ),
        migrations.CreateModel(
            name='RefundItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price_at_refund', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_price_row', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='sales.saleitems')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.refundattributes')),
            ],
            options={
                'verbose_name': 'Refund Item',
                'verbose_name_plural': 'Refund Items',
            },
        ),
    ]
