# Generated by Django 6.0.4 on 2026-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_refundattributes_refunditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='fiscal_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='fiscal_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='fiscal_status',
            field=models.CharField(choices=[('NONE', 'Not fiscalized'), ('PRINTED', 'Printed'), ('FAILED', 'Failed')], default='NONE', max_length=7),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='fiscal_unic_sale_num',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
