# Generated by Django 6.0.4 on 2026-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_fiscalcounter_saleattributes_fiscal_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundattributes',
            name='fiscal_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refundattributes',
            name='fiscal_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundattributes',
            name='fiscal_status',
            field=models.CharField(choices=[('NONE', 'Not fiscalized'), ('PRINTED', 'Printed'), ('FAILED', 'Failed')], default='NONE', max_length=7),
        ),
        migrations.AddField(
            model_name='refundattributes',
            name='fiscal_unic_sale_num',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='saleattributes',
            name='fiscal_receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
