# Generated by Django 6.0.4 on 2026-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_refundattributes_fiscal_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundattributes",
            name="fiscal_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Not fiscalized"),
                    ("PRINTED", "Printed"),
                    ("FAILED", "Failed"),
                    ("PENDING", "Waiting to print"),
                ],
                default="NONE",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="saleattributes",
            name="fiscal_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Not fiscalized"),
                    ("PRINTED", "Printed"),
                    ("FAILED", "Failed"),
                    ("PENDING", "Waiting to print"),
                ],
                default="NONE",
                max_length=7,
            ),
        ),
    ]
