# Generated by Django 6.0.4 on 2026-09-07 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliveryattributes_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitems',
            name='delivery_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity Delivered'),
        ),
    ]
