# Generated by Django 6.0.4 on 2026-09-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_finalize_document_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
