# Generated by Django 6.0.4 on 2026-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_alter_documenttype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitems',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
