# Generated by Django 6.0.4 on 2026-09-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_deliveryitems_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattributes',
            name='movement_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('WRITE_OFF', 'Write-off')], default='DELIVERY', max_length=10, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='deliveryattributes',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='deliveryattributes',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='deliveries.documenttype', verbose_name='Document Type'),
        ),
    ]
