# Generated by Django 6.0.4 on 2026-09-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_deliveryattributes_movement_type_and_more'),
        ('products', '0010_productchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Scrap Reason',
                'verbose_name_plural': 'Scrap Reasons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deliveryitems',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapped_as', to='deliveries.deliveryitems', verbose_name='Source Batch'),
        ),
        migrations.AlterField(
            model_name='deliveryattributes',
            name='movement_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('WRITE_OFF', 'Write-off'), ('SCRAP', 'Scrap')], default='DELIVERY', max_length=10, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='deliveryattributes',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='products.suppliers', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='deliveryitems',
            name='scrap_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrap_items', to='deliveries.scrapreason', verbose_name='Scrap Reason'),
        ),
    ]
