# Generated by Django 6.0.4 on 2026-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_scrapreason_deliveryitems_source_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattributes',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
