# Generated by Django 6.0.4 on 2026-09-24 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_deliveryattributes_comment'),
        ('products', '0013_productsupplier_linked_from_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItemRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_at_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('original_delivery_time', models.DateTimeField()),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_removals', to='products.product')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_item_removals', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.suppliers')),
            ],
            options={
                'verbose_name': 'Delivery Item Removal',
                'verbose_name_plural': 'Delivery Item Removals',
                'ordering': ['-removed_at'],
            },
        ),
    ]
