"""
Django settings for STORA project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Real secrets (SECRET_KEY, DB password, ...) live in a local .env file, never
# in git. On a dev machine with no .env, every os.environ.get() below falls
# back to the old hardcoded dev values, so nothing changes for that workflow.
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-b55d(03n2a=%bcefdf&nr@t!g(4oujyye@_ats)#w#sgf7)a*u'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Needed only behind a reverse proxy that terminates TLS itself (e.g. Railway,
# any cloud host) -- the app receives plain HTTP from the proxy and would
# otherwise think every request is insecure, breaking CSRF checks on POSTs
# made over real HTTPS. The Windows pilot (waitress with no proxy in front,
# see DEPLOYMENT.md) never sends this header, so this is a no-op there.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',

    'STORA.core',
    'STORA.accounts',
    'STORA.products',
    'STORA.sales',
    'STORA.deliveries',
    'STORA.reports',
    'STORA.revisions',
    'STORA.pricelists',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'STORA.core.middleware.CashierOperationSessionMiddleware',
]

ROOT_URLCONF = 'STORA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'STORA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'stora_db'),
        'USER': os.environ.get('DB_USER', 'stora_usr'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'stora_psswd'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
    # Used only by the Reports app's AI mode (natural-language report
    # generation) -- a separate Postgres role with SELECT-only grants (see
    # db_create_ai_readonly_role.sql), not just the same connection with a
    # "please don't write" instruction in the prompt. Genuinely can't
    # execute a write, regardless of what the AI generates.
    'readonly': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'stora_db'),
        'USER': os.environ.get('DB_READONLY_USER', 'stora_ai_readonly'),
        # Same dev-only fallback pattern as DB_PASSWORD above -- matches
        # what db_create_ai_readonly_role.sql actually set locally, so dev
        # works without needing a .env file (same reasoning as DB_PASSWORD).
        'PASSWORD': os.environ.get('DB_READONLY_PASSWORD', 'stora_psswd'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
}


AUTH_USER_MODEL = 'accounts.Employee'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Target for `collectstatic`; WhiteNoise serves everything from here once
# DEBUG=False, so runserver's own static-file shortcut is no longer needed.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Not the Manifest variant -- that needs `collectstatic` to have run
        # first (breaks tests/dev) and would duplicate the cache-busting the
        # project already does itself via {% static_v %} (core/templatetags/
        # cache_bust.py).
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days

# Reports app "AI mode" -- natural-language report generation. Queries run
# through the genuinely read-only 'readonly' DB connection above (see
# db_create_ai_readonly_role.sql), not this key -- the key is only for
# talking to the Anthropic API itself. No fallback default: the AI report
# views check for this being empty and show a friendly message instead of
# crashing, rather than silently pretending a placeholder key would work.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_REPORTS_MODEL = os.environ.get('AI_REPORTS_MODEL', 'claude-sonnet-5')

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Sofia'

# With DEBUG=False the browser no longer shows a traceback -- this is the
# only place a real error is still visible. Rotates so it can't grow
# unbounded on a machine nobody is watching.
(BASE_DIR / 'logs').mkdir(exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'stora.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
