# Generated by Django 6.0.4 on 2026-09-18 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Question')),
                ('generated_sql', models.TextField(blank=True)),
                ('last_answer', models.TextField(blank=True, verbose_name='Last narrative answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Report',
                'verbose_name_plural': 'AI Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
