# Generated by Django 6.0.4 on 2026-09-06 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='code',
            field=models.CharField(blank=True, help_text='Scan the barcode or enter the EAN-13 number', max_length=13, null=True, unique=True, verbose_name='Barcode number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='bulstat',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bulstat', message='BULSTAT must contain only digits', regex='^\\d+$')], verbose_name='BULSTAT'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='vat_n',
            field=models.CharField(blank=True, help_text='Only if the company is VAT registered!', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT number must start with BG followed by digits', regex='^BG\\d+$')], verbose_name='VAT:'),
        ),
    ]
