# Generated by Django 6.0.4 on 2026-09-07 09:28

import django.db.models.deletion
from django.db import migrations, models


def copy_supplier_links_to_through_model(apps, schema_editor):
    """The M2M is switching from an auto-managed join table to the explicit
    ProductSupplier table -- Django doesn't carry the old links over on its
    own, so copy them here (numbering each product's existing suppliers 1,
    2, 3... in whatever order they were already returned in)."""
    Product = apps.get_model('products', 'Product')
    ProductSupplier = apps.get_model('products', 'ProductSupplier')
    for product in Product.objects.all():
        for position, supplier in enumerate(product.supplier.all(), start=1):
            ProductSupplier.objects.create(product=product, supplier=supplier, position=position)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_barcode_code_alter_product_sell_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Barcode', 'verbose_name_plural': 'Barcodes'},
        ),
        migrations.AddField(
            model_name='barcode',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = primary barcode, 2+ = alternates', verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='1 = primary supplier, 2+ = alternates', verbose_name='Position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='products.suppliers')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(copy_supplier_links_to_through_model, noop_reverse),
        # Django can't ALTER a plain M2M into a through= M2M in place (it
        # refuses -- "you cannot add or remove through= on M2M fields").
        # The RunPython step above already copied the data out of the old
        # auto-managed join table, so it's safe to drop that field and add
        # the through-based one back under the same name.
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductSupplier', to='products.suppliers'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='unique_product_supplier'),
        ),
    ]
