# Generated by Django 6.0.4 on 2026-09-07 10:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_barcode_options_barcode_position_and_more'),
        # pg_trgm must be enabled before a gin_trgm_ops index can be created.
        ('core', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='category_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['internal_code'], name='product_code_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='suppliers',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='supplier_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
