# Generated by Django 6.0.4 on 2026-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_category_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Piece (pcs)'), ('weight', 'Weight (kg)')], default='piece', help_text='Piece: whole units (bottles, packs). Weight: sold by the kg (produce, deli).', max_length=6, verbose_name='sold by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Can be negative if items are sold before delivery is recorded', max_digits=10, verbose_name='stock quantity'),
        ),
    ]
