# Generated by Django 6.0.4 on 2026-09-08 06:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_unit_type_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_backfilled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recipe',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, selling this product deducts stock from its ingredients instead of its own quantity (e.g. a cappuccino made from milk + coffee).', verbose_name='Made from other products (recipe)'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text="In the ingredient's own unit (kg for weight, pcs for piece).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity per unit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='products.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='products.product')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient')],
            },
        ),
    ]
