# Generated by Django 6.0.4 on 2026-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_ingredients_backfilled_at_product_is_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='is_scale_code',
            field=models.BooleanField(default=False, help_text='Check this if the barcode above is a 7 or 8 digit scale-printed prefix (not a full barcode) -- the scale encodes weight/quantity after it.', verbose_name='Scale (weighing) barcode prefix'),
        ),
    ]
