# Generated by Django 6.0.4 on 2026-09-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_pos',
            field=models.BooleanField(default=False, help_text='If checked, this category appears as a folder button on the cash register screen.', verbose_name='Show on POS screen'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_pos',
            field=models.BooleanField(default=False, help_text='If checked, this product appears as a button when its category is opened on the cash register screen.', verbose_name='Show on POS screen'),
        ),
    ]
