# Generated by Django 6.0.4 on 2026-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_show_on_pos_product_show_on_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='linked_from_delivery',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
