# Generated by Django 6.0.4 on 2026-09-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productsupplier_linked_from_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hides this product from the everyday Products list without deleting its history.', verbose_name='Archived'),
        ),
    ]
