# Generated by Django 6.0.4 on 2026-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxgroup',
            name='fiscal_letter',
            field=models.CharField(blank=True, max_length=1, verbose_name='Fiscal device letter'),
        ),
    ]
