# Generated by Django 6.0.4 on 2026-10-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_taxgroup_fiscal_letter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="suppliers",
            options={"verbose_name": "Supplier", "verbose_name_plural": "Suppliers"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="products.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="internal_code",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="internal code"
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="taxgroup",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="name"),
        ),
    ]
