# Generated by Django 6.0.4 on 2026-09-17 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_category_show_on_pos_product_show_on_pos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions_started', to=settings.AUTH_USER_MODEL, verbose_name='Started By')),
            ],
            options={
                'verbose_name': 'Stock Revision',
                'verbose_name_plural': 'Stock Revisions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('system_quantity_at_start', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_at_revision', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_items', to='products.product')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='revisions.revisionattributes')),
            ],
            options={
                'verbose_name': 'Revision Item',
                'verbose_name_plural': 'Revision Items',
            },
        ),
        migrations.AddConstraint(
            model_name='revisionattributes',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='only_one_open_revision'),
        ),
        migrations.AddConstraint(
            model_name='revisionitems',
            constraint=models.UniqueConstraint(fields=('revision', 'product'), name='one_row_per_product_per_revision'),
        ),
    ]
