# Generated by Django 6.0.4 on 2026-09-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionattributes',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10),
        ),
    ]
