# Generated by Django 6.0.4 on 2026-09-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0002_alter_revisionattributes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionattributes',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
