# Generated by Django 6.0.4 on 2026-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revisions", "0003_revisionattributes_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionitems",
            name="quantity_before_complete",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
