# Generated by Django 6.0.4 on 2026-09-07 10:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_phone'),
        ('auth', '0012_alter_user_first_name_max_length'),
        # pg_trgm must be enabled before a gin_trgm_ops index can be created.
        ('core', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='employee_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='employee_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='employee_username_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
