# Generated by Django 6.0.4 on 2026-09-27 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Company name')),
                ('bulstat', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_bulstat', message='BULSTAT must contain only digits', regex='^\\d+$')], verbose_name='BULSTAT')),
                ('vat_n', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT number must start with BG followed by digits', regex='^BG\\d+$')], verbose_name='VAT number')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Site address')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
