# Generated by Django 6.0.4 on 2026-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='orderattributes',
            name='order_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='orderattributes',
            name='supplier_position',
            field=models.CharField(blank=True, max_length=20, verbose_name='Supplier position(s)'),
        ),
    ]
