# Generated by Django 6.0.4 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordercounter_alter_orderattributes_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattributes',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (AI)'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=10, verbose_name='Status'),
        ),
    ]
